"use server";

import { GoogleGenAI } from "@google/genai";
import * as cheerio from "cheerio";

// Initialize Gemini Client
const aiClient = () => {
  const key = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
  if (!key || key === "your-api-key") {
    throw new Error("NEXT_PUBLIC_GEMINI_API_KEY environment variable is missing or invalid. Please check your secrets/environment variables.");
  }
  return new GoogleGenAI({ apiKey: key });
};

export async function runAISchemaExtraction(url: string, schemaDefinition: string) {
  try {
    // 1. Fetch HTML
    const res = await fetch(url, {
      headers: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) NexusCrawl/1.0" },
      next: { revalidate: 3600 }
    });
    
    if (!res.ok) throw new Error(`Failed to fetch URL: ${res.statusText}`);
    const html = await res.text();
    
    // 2. Parse and clean HTML to save tokens
    const $ = cheerio.load(html);
    
    // Remove scripts, styles, svgs to compress dom
    $('script, style, svg, path, link, meta, noscript').remove();
    
    // Extract main text content. In a real scenario we might send structured markdown.
    let cleanText = $('body').text().replace(/\s+/g, ' ').trim();
    // Truncate to avoid massive token limits (Gemini 2.5 Flash handles 1M, but let's be safe for latency)
    cleanText = cleanText.substring(0, 100000); 

    // 3. Prompt Gemini
    const prompt = `
      You are an expert data extraction agent (SCRIBES pattern). 
      I will provide you the cleaned text content extracted from a webpage, and a JSON Schema representing the required data.
      
      Extract the requested data from the text and return ONLY valid, minified JSON matching the requested schema. Return {} if nothing matches.
      
      TARGET SCHEMA:
      ${schemaDefinition}
      
      PAGE CONTENT:
      ${cleanText}
    `;

    const response = await aiClient().models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
           responseMimeType: "application/json",
        }
    });

    const outputText = response.text;
    
    if (!outputText) throw new Error("No response generated by model");
    
    const parsedData = JSON.parse(outputText);
    return { success: true, data: parsedData };

  } catch (error) {
    console.error("Extraction error:", error);
    return { success: false, error: String(error) };
  }
}
